// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkLogManager.Infrastructure.Persistence;

#nullable disable

namespace WorkLogManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkLogManagerDbContext))]
    [Migration("20260915164034_AddNoteToEmployeeWorkLog")]
    partial class AddNoteToEmployeeWorkLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkLogManager.Application.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.EmployeeWorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("MonthClosingId")
                        .HasColumnType("uuid")
                        .HasColumnName("month_closing_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employee_work_logs");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_work_logs_employee_id");

                    b.HasIndex("MonthClosingId")
                        .HasDatabaseName("ix_employee_work_logs_month_closing_id");

                    b.ToTable("employee_work_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_work_logs_end_date_after_start_date", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.MonthClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_month_closings");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_month_closings_year_month");

                    b.ToTable("month_closings", null, t =>
                        {
                            t.HasCheckConstraint("ck_month_closings_month_range", "month >= 1 AND month <= 12");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.WorkSchedulePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_work_schedule_periods");

                    b.HasIndex("EmployeeId", "DayOfWeek")
                        .HasDatabaseName("ix_work_schedule_periods_employee_id_day_of_week");

                    b.ToTable("work_schedule_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_schedule_periods_end_after_start", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.EmployeeWorkLog", b =>
                {
                    b.HasOne("WorkLogManager.Application.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_work_logs_employees_employee_id");

                    b.HasOne("WorkLogManager.Application.Entities.MonthClosing", null)
                        .WithMany()
                        .HasForeignKey("MonthClosingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_work_logs_month_closings_month_closing_id");
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.WorkSchedulePeriod", b =>
                {
                    b.HasOne("WorkLogManager.Application.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_schedule_periods_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
