// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkLogManager.Infrastructure.Persistence;

#nullable disable

namespace WorkLogManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkLogManagerDbContext))]
    partial class WorkLogManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("WorkLogManager.Application.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hire_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.EmployeeWorkLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("MonthClosingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("month_closing_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employee_work_logs");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_work_logs_employee_id");

                    b.HasIndex("MonthClosingId")
                        .HasDatabaseName("ix_employee_work_logs_month_closing_id");

                    b.ToTable("employee_work_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_work_logs_end_date_after_start_date", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.MonthClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_month_closings");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_month_closings_year_month");

                    b.ToTable("month_closings", null, t =>
                        {
                            t.HasCheckConstraint("ck_month_closings_month_range", "month >= 1 AND month <= 12");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.SystemParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Param")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("param");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_system_parameters");

                    b.HasIndex("Param", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_system_parameters_param_value");

                    b.ToTable("system_parameters", (string)null);
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.WorkSchedulePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_work_schedule_periods");

                    b.HasIndex("EmployeeId", "DayOfWeek")
                        .HasDatabaseName("ix_work_schedule_periods_employee_id_day_of_week");

                    b.ToTable("work_schedule_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_schedule_periods_end_after_start", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.EmployeeWorkLog", b =>
                {
                    b.HasOne("WorkLogManager.Application.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_work_logs_employees_employee_id");

                    b.HasOne("WorkLogManager.Application.Entities.MonthClosing", null)
                        .WithMany()
                        .HasForeignKey("MonthClosingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_work_logs_month_closings_month_closing_id");
                });

            modelBuilder.Entity("WorkLogManager.Application.Entities.WorkSchedulePeriod", b =>
                {
                    b.HasOne("WorkLogManager.Application.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_schedule_periods_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
